---
title: " Bonus Avanzado (opcional)"
jupyter: python3
author: "Cadena Paul"
date: "10-07-2025"
format: 
    html:
        embed-resources: true
---


# Bonu Avanzado (opcional)
    Integrar IA para clasificaci칩n autom치tica de im치genes o textos (por ejemplo, categorizar tipo de incidencia a partir de una foto o descripci칩n).

 ## Entrega:
    -1. Modelo de imagenes-texto para tener una descripcion a partir de una simple imagen
    -2.  Modelo de Clasificacion a partir de la descripcion del reporte

        1. Este modelo hace uso de un modelo Open SOurce y de libre acceso
        que nos dara una descripcion con solo una imagen de imput, es decir nos explicara la imagen, si subimos una imagen del cielo este modelo de IA sabra explicarnoslo

        2. Se entreno un modelo de IA, se hizo Fine-tuning a otro modelo (bert-base). Basicamente se tomo un modelo de lenguaje de clasificacion y se lo entreno con muchos ejemplos de descripciones para asi que este modelo aprenda a categorizar un modelo a partir de su descripcion es decir: dada una descripcion del reporte, este modelo sabra en cual categoria ponerla(bache, luminaria, grafitti, etc)

Todo se realizo en google collab importante los modelos de codigo libre y entrenandolos en google collab, cualquiera comparto los enlaces a estos modelos para que los prueben 
            
            Imagen: https://colab.research.google.com/drive/15yMGgjKFOXGO2PBdZPeKXVwQ9fe-tB5F?usp=sharing

            Clasificador :https://colab.research.google.com/drive/1vOrGJq04CjlZUK-WijqJkRLOk9t2v8Yp?usp=sharing


## Video Expliacacion
https://youtu.be/TMTnp84gqsU

### Author

    Paul Cadena
    Github: https://github.com/paulscc
    



