project:
  type: website
  output-dir: docs

website:
  title: "MingaFix Report"
  navbar:
    left:
      - href: index.qmd
        text: Primer Reporte
      - href: segundo.qmd
        text: Reto 0-Arquitectura
      - href: tercer.qmd
        text: Reto 1-API Ciudadana Básica

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
    mermaid: {}
  # <-- debe ir aquí

jupyter:
  kernelspec:
    name: ml1
    language: python
    display_name: "Python (ml1)"
