project:
  type: website
  output-dir: docs

website:
  title: "MingaFix Report"
  navbar:
    left:
      - text: "Semana 1"
        menu:
          - href: index.qmd
            text: Primer Reporte
          - href: segundo.qmd
            text: Reto 0-Arquitectura
          - href: tercer.qmd
            text: Reto 1-API Ciudadana Básica
          - href: cuarto.qmd
            text: Reto 2 – Mapa Vivo Inicial
          - href: quinto.qmd
            text: Reto 3 – Creativo-Comunitario 
      - text: "Semana 2"
        menu:
          - href: 2primer.qmd
            text: Reto 1 Supabase Connection & Data Handling
          - href: 2segundo.qmd
            text: Reto 2 – LiveMap API Integration
          - href: 2tercero.qmd
            text: Reto 3 – Live Updates Simulation (Polling)

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
    mermaid: {}
  # <-- debe ir aquí

jupyter:
  kernelspec:
    name: ml1
    language: python
    display_name: "Python (ml1)"
